--------------Creacion de tabla TMA_ADJUSTMENTS_TMP, primera materializacion de V_TMA_ADJUSTMENTS --------------------

DROP table if exists WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT;

create table WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT
as
select 
B.UTILIZATION_ID AS UTILIZATION_ID,
B.UTILIZATION_TYPE AS UTILIZATION_TYPE,                                    
B.FUND_ID AS FUND_ID,
B.AMOUNT AS AMOUNT,
B.CURRENCY_CODE AS CURRENCY_CODE,
B.GL_DATE AS ADJUSTMENT_DATE,
B.UNIV_CURR_AMOUNT AS UNIV_CURR_AMOUNT,
B.ORDER_LINE_ID,
B.PRODUCT_ID,
AC.CUSTOMER_NAME,
OZF.QP_LIST_HEADER_ID AS OFFER_ID,
OZF.OFFER_TYPE AS OFFER_TYPE,
OZF.OFFER_CODE AS OFFER_CODE,
OZF.OFFER_AMOUNT AS OFFER_AMOUNT,
OZF.STATUS_CODE AS OFFER_STATUS_CODE,
OZF.LUMPSUM_AMOUNT AS LUMPSUM_AMOUNT,
OZF.LUMPSUM_PAYMENT_TYPE AS LUMPSUM_PAYMENT_TYPE,
CND.WEEK AS WEEK,
CND.FISCAL_YEAR AS FISCAL_YEAR,
CND.PERIOD AS FISCAL_PERIOD,
AMOUNT AS UTILIZED_AMOUNT,
CASE WHEN (B.UTILIZATION_TYPE IN ('ADJUSTMENT', 'ACCRUAL') AND B.ORDER_LINE_ID IS NULL AND cast(CND.WEEK as int) = 43) THEN AMOUNT ELSE 0 END AS INITIAL_UPDATE,
CASE WHEN (UTILIZATION_TYPE = 'ADJUSTMENT' AND  B.ADJUSTMENT_DATE  > '2015-10-24') THEN AMOUNT ELSE 0 END AS ADJUSTMENT_AMOUNT, 
FUNDS.SHORT_NAME AS SHORT_NAME,
FUNDS.DESCRIPTION AS DESCRIPTION,
FUNDB.LAST_UPDATE_DATE AS FUND_LAST_UPDATE, 
FUNDB.ORIGINAL_BUDGET AS FUND_ORIGINAL_BUDGET, 
FUNDB.PLANNED_AMT AS FUND_PLANNED_AMT, 
FUNDB.COMMITTED_AMT AS FUND_COMMITTED_AMT, 
FUNDB.EARNED_AMT AS FUND_EARNED_AMT, 
FUNDB.PAID_AMT AS FUND_PAID_AMT, 
FUNDB.UTILIZED_AMT AS FUND_UTILIZED_AMT
FROM erp_pgbari_sz.OZF_FUNDS_UTILIZED_ALL_B_OZF B
INNER JOIN erp_pgbari_sz.OZF_OFFERS_OZF OZF ON B.PLAN_ID = OZF.QP_LIST_HEADER_ID
INNER JOIN DWH_OPERERP_CANADA.CN_CALENDAR CND ON substr(B.ADJUSTMENT_DATE,1,10) = CND.BILL_DATE
INNER JOIN erp_pgbari_sz.OZF_FUNDS_ALL_TL_OZF FUNDS ON B.FUND_ID = FUNDS.FUND_ID
INNER JOIN erp_pgbari_sz.OZF_FUNDS_ALL_B_OZF FUNDB ON FUNDB.FUND_ID = FUNDS.FUND_ID
LEFT JOIN erp_pgbari_sz.AR_CUSTOMERS_APPS AC ON B.BILLTO_CUST_ACCOUNT_ID =  AC.CUSTOMER_ID
LEFT JOIN erp_pgbari_sz.AR_CUSTOMERS_APPS AC2 ON B.CUST_ACCOUNT_ID = AC2.CUSTOMER_ID
LEFT JOIN erp_pgbari_sz.AR_CUSTOMERS_APPS AC3 ON OZF.QUALIFIER_ID = AC3.CUSTOMER_ID
LEFT JOIN (SELECT DISTINCT INVENTORY_ITEM_ID,ACTIVITY_PRODUCT_ID FROM erp_pgbari_sz.AMS_ACT_PRODUCTS_AMS) AMT ON OZF.OFFER_ID = AMT.ACTIVITY_PRODUCT_ID
LEFT JOIN (SELECT DISTINCT INVENTORY_ITEM_ID, SEGMENT1 FROM erp_pgbari_sz.MTL_SYSTEM_ITEMS_FVL_APPS) FVL ON FVL.INVENTORY_ITEM_ID = AMT.INVENTORY_ITEM_ID 
WHERE cast(B.ORG_ID as string) = '714'  AND B.FUND_ID BETWEEN 10001 AND 10009 AND FUNDS.LANGUAGE = 'US' AND B.AMOUNT <> 0;


-----------------Materializa la vista V_CUSTOMER ---------------------------


drop table if exists WRK_GLOBAL.T_V_CUSTOMERS;

create table WRK_GLOBAL.T_V_CUSTOMERS
as
select * from WRK_GLOBAL.V_CUSTOMERS;



--------------Creacion de tabla TMA_ADJUSTMENTS_TMP1, segunda materializacion de V_TMA_ADJUSTMENTS --------------------

DROP TABLE if exists WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT1;

CREATE TABLE WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT1
as
select 
tmp.*,
ORD.PRICING_QUANTITY AS QUANTITY,
ORD.PRICING_QUANTITY_UOM AS PRICING_QUANTITY_UOM,
ORD.UNIT_SELLING_PRICE AS UNIT_SELLING_PRICE,
ORD.UNIT_LIST_PRICE AS UNIT_LIST_PRICE,
ORD.LINE_CATEGORY_CODE AS ORDER_TYPE,
ORD.FLOW_STATUS_CODE AS FLOW_STATUS_CODE,
ORD.LINE_CATEGORY_CODE AS LINE_CATEGORY_CODE,
ORD.INVENTORY_ITEM_ID,
HCASA.PARTY_SITE_ID,
CASE WHEN ORD.ORDERED_ITEM LIKE '11%' THEN ORD.ORDERED_ITEM WHEN SYS.SEGMENT1 IS NOT NULL THEN SYS.SEGMENT1 ELSE SYS2.SEGMENT1 END AS ORDERED_ITEM
FROM WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT TMP
LEFT JOIN erp_pgbari_sz.OE_ORDER_LINES_ALL_ONT ORD ON TMP.ORDER_LINE_ID =ORD.LINE_ID
LEFT JOIN (SELECT DISTINCT INVENTORY_ITEM_ID, DESCRIPTION, SEGMENT1 FROM erp_pgbari_sz.MTL_SYSTEM_ITEMS_B_INV) SYS ON SYS.INVENTORY_ITEM_ID = ORD.INVENTORY_ITEM_ID
LEFT JOIN erp_pgbari_sz.HZ_CUST_SITE_USES_ALL_AR HCSUA ON ORD.SHIP_TO_ORG_ID = HCSUA.SITE_USE_ID
LEFT JOIN erp_pgbari_sz.HZ_CUST_ACCT_SITES_ALL_AR HCASA ON HCSUA.CUST_ACCT_SITE_ID = HCASA.CUST_ACCT_SITE_ID
LEFT JOIN (SELECT DISTINCT INVENTORY_ITEM_ID, DESCRIPTION, SEGMENT1 FROM erp_pgbari_sz.MTL_SYSTEM_ITEMS_B_INV) SYS2 ON SYS2.INVENTORY_ITEM_ID = TMP.PRODUCT_ID;




---------insert into table DWH_OPERERP_CANADA.TMA_ADJUSTMENTS_TMP2 tercera materializacion de V_TMA_ADJUSTMENTS --------------------

DROP TABLE if exists WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT2;

create table WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT2
as
select 
tmp1.*,
CUS.CUSTOMERORACLE_ID AS CUSTOMERORACLE_ID,
CASE WHEN tmp1.CUSTOMER_NAME IS NOT NULL THEN tmp1.CUSTOMER_NAME WHEN CUS.BANNER_CUSTOMER_NAME IS NOT NULL THEN CUS.BANNER_CUSTOMER_NAME ELSE tmp1.CUSTOMER_NAME END AS BANNER_CUSTOMER_NAME,
CASE WHEN FLOW_STATUS_CODE = 'CLOSED' THEN AMOUNT ELSE 0 END AS ACCRUAL_AMOUNT,
CASE WHEN (OFFER_TYPE = 'LUMPSUM' AND UTILIZATION_TYPE = 'ACCRUAL' AND  TMP1.ADJUSTMENT_DATE  > '2015-10-24') THEN AMOUNT ELSE 0 END AS ACCRUAL_LUMPSUM_AMOUNT,
COALESCE (CASE WHEN FLOW_STATUS_CODE = 'CLOSED' THEN AMOUNT ELSE 0 END + CASE WHEN (UTILIZATION_TYPE = 'ADJUSTMENT' AND TMP1.ADJUSTMENT_DATE  > '2015-10-24') THEN AMOUNT ELSE 0 END + CASE WHEN (OFFER_TYPE = 'LUMPSUM' AND UTILIZATION_TYPE = 'ACCRUAL' AND  TMP1.ADJUSTMENT_DATE  > '2015-10-24') THEN AMOUNT ELSE 0 END ,0) AS TOTAL_EARNED_AMOUNT
FROM WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT1 TMP1
LEFT JOIN WRK_GLOBAL.T_V_CUSTOMERS CUS ON CUS.CUSTOMERORACLE_ID = TMP1.PARTY_SITE_ID;



---------CREATING FINAL VIEW FROM TEMPORAL TABLES ----------------------------------------

CREATE TABLE STG_DSD_Canada.T_TMA_ADJUSTMENT
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
location 's3a://devbimboaws/DEV_CANADA_IC/Data/tg_dsd_canada/T_TMA_ADJUSTMENT'
as
select * from WRK_GLOBAL.TMA_ADJUSTMENTS_WRKT2;








